version: '3'
services:

  servercode:
    build: ./code
    volumes:
      - ./code:/code
    restart: 'always'
    links:
      - mongo
      - redis
    expose:
      - 5000

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - servercode

  mongo:
    image: mongo:latest
    restart: always
    expose:
      - 27017

  redis:
    image: redis:latest
    expose:
      - 6379
    restart: always