version: '3'

services:
  web:
    build: ./code
    volumes:
      - web-data:/usr/src/app/static
    restart: always
    links:
      - mongo
      - redis
    expose:
      - 5000
    command: /usr/local/bin/gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 2 backend/server:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - web:web

  mongo:
    image: mongo:latest
    restart: always
    expose:
      - 27017

  redis:
    image: redis:latest
    expose:
      - 6379
    restart: always

volumes:
  web-data:
    driver: local
    driver_opts: 
      type: none
      device: $PWD/code/frontend/buzzer-io/dist/buzzer-io
      o: bind