FROM ubuntu:latest
USER root
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN apt-get -y install python3-pip
RUN curl -sL https://deb.nodesource.com/setup_14.x  | bash -
RUN apt-get -y install nodejs
RUN npm install -g @angular/cli
RUN npm install ngx-socket-io
RUN mkdir /code
WORKDIR /code
ADD requirements.txt .
RUN pip3 install -r requirements.txt
CMD ["python3", "server.py"]
EXPOSE 5000
